name: golangci-lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  lint:
    name: Run golangci lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 #v2.4.0
      - uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a #v2.1.5
        with:
          go-version: '1.18'
      - uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376
        with:
          only-new-issues: true
