name: golangci-lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  lint:
    name: Run golangci lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v2.4.0
      - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 #v2.1.5
        with:
          go-version: '1.18'
      - uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5
        with:
          only-new-issues: true
